# 张量教程

### 1. 张量

In [1]:
from __future__ import print_function

import torch
import numpy as np

#### 1.1 创建 5x3 的矩阵, 未初始化

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -2.5244e-29,  1.3873e+14],
        [ 1.0845e-19,  1.1210e-44, -0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  3.5873e-43],
        [ 3.6013e-43,  3.5873e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


#### 1.2 创建 5x3 的矩阵, 随机初始化

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7916, 0.7597, 0.3735],
        [0.7063, 0.3497, 0.0846],
        [0.4522, 0.7975, 0.2900],
        [0.5683, 0.0825, 0.9277],
        [0.2307, 0.2631, 0.1039]])


#### 1.3 创建 5x3 的矩阵, 用0填充, 类型为 long

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


#### 1.4 直接用数据创建张量

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


#### 1.5 用已存在的张量创建新的张量

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.8487, 0.0163, 0.9423],
        [0.7362, 0.7762, 0.7327],
        [0.7682, 0.7142, 0.6317],
        [0.3266, 0.2866, 0.4226],
        [0.2450, 0.0939, 0.2432]])


#### 1.6 获取张量的大小

In [8]:
print(x.size())

torch.Size([5, 3])


### 2. 运算

#### 2.1 加法: +

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.1466, 0.0919, 1.0085],
        [1.1580, 1.0694, 0.7849],
        [1.0028, 1.6734, 1.0641],
        [0.9071, 0.8722, 1.1413],
        [0.4387, 0.2982, 0.3702]])


#### 2.2 加法: torch.add

In [10]:
print(torch.add(x, y))

tensor([[1.1466, 0.0919, 1.0085],
        [1.1580, 1.0694, 0.7849],
        [1.0028, 1.6734, 1.0641],
        [0.9071, 0.8722, 1.1413],
        [0.4387, 0.2982, 0.3702]])


#### 2.3 加法: 提供一个用于输出结果张量的参数

In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.1466, 0.0919, 1.0085],
        [1.1580, 1.0694, 0.7849],
        [1.0028, 1.6734, 1.0641],
        [0.9071, 0.8722, 1.1413],
        [0.4387, 0.2982, 0.3702]])


#### 2.4 加法: add_

In [12]:
y.add_(x)
print(y)

tensor([[1.1466, 0.0919, 1.0085],
        [1.1580, 1.0694, 0.7849],
        [1.0028, 1.6734, 1.0641],
        [0.9071, 0.8722, 1.1413],
        [0.4387, 0.2982, 0.3702]])


#### 2.5 查看元素

In [13]:
print(x[:, 1])

tensor([0.0163, 0.7762, 0.7142, 0.2866, 0.0939])


#### 2.6 调整大小 torch.view

In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


#### 2.7 .item()

In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.5374])
-1.5373741388320923


### 3. NumPy 桥接

#### 3.1 torch 张量转换为 NumPy 数组

In [16]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)  # torch tensor 与 numpy array 共享底层内存空间, 修改其中一个, 将影响另一个的值

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### 3.2 NumPy 数组转换为 torch 张量

In [18]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### 4. CUDA 张量

通过 .to 方法, 张量可以移动到任意的设备中

In [19]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))