# 张量教程

### 1. 张量

In [1]:
from __future__ import print_function

import torch
import numpy as np

#### 1.1 创建 5x3 的矩阵, 未初始化

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -3.6893e+19,  0.0000e+00],
        [-3.6893e+19,  1.4569e-19,  2.7517e+12],
        [ 7.5338e+28,  3.0313e+32,  6.3828e+28],
        [ 1.4603e-19,  1.0899e+27,  6.8943e+34],
        [ 1.1835e+22,  7.0976e+22,  1.8515e+28]])


#### 1.2 创建 5x3 的矩阵, 随机初始化

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4981, 0.2493, 0.9576],
        [0.5467, 0.0314, 0.0659],
        [0.2471, 0.1726, 0.0306],
        [0.9842, 0.6943, 0.7038],
        [0.8391, 0.5787, 0.7176]])


#### 1.3 创建 5x3 的矩阵, 用0填充, 类型为 long

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


#### 1.4 直接用数据创建张量

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


#### 1.5 用已存在的张量创建新的张量

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.7961, 0.4875, 0.7720],
        [0.3888, 0.8087, 0.4540],
        [0.7322, 0.0304, 0.3662],
        [0.5279, 0.8537, 0.8524],
        [0.1928, 0.8679, 0.9585]])


#### 1.6 获取张量的大小

In [8]:
print(x.size())

torch.Size([5, 3])


### 2. 运算

#### 2.1 加法: +

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.2005, 0.6044, 1.6072],
        [0.6853, 1.2877, 1.3257],
        [1.0827, 0.0907, 0.9769],
        [1.4238, 1.7794, 1.8471],
        [0.7541, 1.7960, 1.5667]])


#### 2.2 加法: torch.add

In [10]:
print(torch.add(x, y))

tensor([[1.2005, 0.6044, 1.6072],
        [0.6853, 1.2877, 1.3257],
        [1.0827, 0.0907, 0.9769],
        [1.4238, 1.7794, 1.8471],
        [0.7541, 1.7960, 1.5667]])


#### 2.3 加法: 提供一个用于输出结果张量的参数

In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.2005, 0.6044, 1.6072],
        [0.6853, 1.2877, 1.3257],
        [1.0827, 0.0907, 0.9769],
        [1.4238, 1.7794, 1.8471],
        [0.7541, 1.7960, 1.5667]])


#### 2.4 加法: add_

In [12]:
y.add_(x)
print(y)

tensor([[1.2005, 0.6044, 1.6072],
        [0.6853, 1.2877, 1.3257],
        [1.0827, 0.0907, 0.9769],
        [1.4238, 1.7794, 1.8471],
        [0.7541, 1.7960, 1.5667]])


#### 2.5 查看元素

In [13]:
print(x[:, 1])

tensor([0.4875, 0.8087, 0.0304, 0.8537, 0.8679])


#### 2.6 调整大小 torch.view

In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


#### 2.7 .item()

In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.1545])
1.1545144319534302


### 3. NumPy 桥接

#### 3.1 torch 张量转换为 NumPy 数组

In [16]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)  # torch tensor 与 numpy array 共享底层内存空间, 修改其中一个, 将影响另一个的值

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### 3.2 NumPy 数组转换为 torch 张量

In [18]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### 4. CUDA 张量

通过 .to 方法, 张量可以移动到任意的设备中

In [19]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))